### ISSUE TITLE
pip2pi downloads but fails to include build-time requirements

### ISSUE THREAD

**Issue by TexasDex** [wolever/pip2pi#38]
I was trying to create a repo for installing protobuf, which depends on google-apputils.  I ran into two different issues:  Pip2pi crashes upon trying to add packages that require the 'ez-setup' package, and pip2pi automatically downloads and installs the 'distribute' package when required, but doesn't include it in the repo it creates.
```
$ pip2pi ../pip_repo/ google-apputils
[...]
    import ez_setup
ImportError: No module named ez_setup

$ pip2pi ../pip_repo/ google-apputils ez_setup                                                  
Downloading/unpacking google-apputils
  File was already downloaded [...]/pip_repo/google-apputils-0.4.1.tar.gz
  Running setup.py (path:[...]/google-apputils/setup.py) egg_info for package google-apputils
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Extracting in /tmp/tmpq4H5PI
    Now working in /tmp/tmpq4H5PI/distribute-0.6.14
    Building a Distribute egg in /tmp/pip_build_USERNAME/google-apputils
    /tmp/pip_build_USERNAME/google-apputils/distribute-0.6.14-py2.7.egg
```

But `../pip_repo` doesn't include the distribute package!  This is a problem if I want to make a repo to install those packages on a machine with no internet connection.

**Comment by wolever** [comment]
Hey,

It looks like the google-apputils package needs to have ez-setup installed before it can be processed. You'll need to run `pip install ez-setup`  before you can run `pip2pi … google-apputils`, and `pip2pi … ez-setup` if you want ez-setup to be included in the pip2pi repo.

Unfortunately there isn't much that pip2pi can sensibly do about this, since it's a somewhat package-specific issue.

**Comment by rwhenderson** [comment]
I've been trying to reslove this. Any help?
```
[randall@neawanna-cent6 apps]$ pip2pi /apps protobuf==3.1.0.post1
DEPRECATION: pip install --download has been deprecated and will be removed in the future. Pip now has a download command that should be used instead.
Collecting protobuf==3.1.0.post1
  File was already downloaded /apps/protobuf-3.1.0.post1-py2.py3-none-any.whl
Collecting six>=1.9 (from protobuf==3.1.0.post1)
  File was already downloaded /apps/six-1.10.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf==3.1.0.post1)
  File was already downloaded /apps/setuptools-28.3.0-py2.py3-none-any.whl
Successfully downloaded protobuf six setuptools

Done. 0 new archives currently saved in '/apps'.
Traceback (most recent call last):
  File "/usr/local/bin/pip2pi", line 11, in <module>
    sys.exit(pip2pi())
  File "/usr/local/lib/python2.7/site-packages/libpip2pi/commands.py", line 510, in pip2pi
    res = _dir2pi(option, subcmd_argv)
  File "/usr/local/lib/python2.7/site-packages/libpip2pi/commands.py", line 290, in _dir2pi
    pkg_name, pkg_rest = file_to_package(pkg_basename, pkgdir)
  File "/usr/local/lib/python2.7/site-packages/libpip2pi/commands.py", line 123, in file_to_package
    raise InvalidFilePackageName(file, basedir)
libpip2pi.commands.InvalidFilePackageName: unexpected file name: 'pip2pi-master.zip' (not in 'pkg-name-version.xxx' format; found in directory: '/apps')

```

**Comment by wolever** [comment]
@rwhenderson it looks like you've got a `pip2pi-master.zip` file lying around in the package repo. You'll need to remove that before it'll work.
