### ISSUE TITLE
pip 19.3 breaks pip2pi 0.8.1

### ISSUE THREAD

**Issue by gary-jackson** [wolever/pip2pi#94]
The latest version of pip breaks pip2pi:

```
$ pip2pi index six==1.12                                                                                      
Traceback (most recent call last):                                                                         
  File "/zzz/bin/pip2pi", line 8, in <module>                                                                                                                                             
    sys.exit(pip2pi())                                                                                     
  File "/zzz/lib/python3.7/site-packages/libpip2pi/commands.py", line 555, in pip2pi                                                                                                      
    res = pip2tgz(subcmd_argv)                                                                             
  File "/zzz/lib/python3.7/site-packages/libpip2pi/commands.py", line 90, in maintain_cwd_helper                                                                                          
    return f(*args, **kwargs)                                                                              
  File "/zzz/lib/python3.7/site-packages/libpip2pi/commands.py", line 440, in pip2tgz                                                                                                     
    pip_run_command(pip_download_command.split() + [outdir] + argv[2:])                                    
  File "/zzz/lib/python3.7/site-packages/libpip2pi/commands.py", line 184, in pip_run_command                                                                                             
    res = pip_main(pip_args)                                                                               
TypeError: 'module' object is not callable
$
```

For now, rolling back to pip 19.2.3 has fixed the problem.

**Comment by SuperSandro2000** [comment]
I can confirm this. Downgrading is not really an easy option for me.

**Comment by Julian** [comment]
First time trying to run this and encountering this issue too -- considering pip's API isn't public, and that all a quick look at the code seems to suggest is that the implementation here assembles command line arguments, is there a reason that doesn't just get executed as a subprocess (and therefore use pip's public API)?

**Comment by mgarnica** [comment]
I have created a PR that fixes this issue, this commit broke pip2pi https://github.com/pypa/pip/commit/09fd200c599de4fadf2ff814a1bef855bc6d77e8 as they moved the main function into a main module.

I'm guessing the issue with having a subprocess is that you'd have to know what the alias for pip is, it could be pip or pip3 or pip3.8 or probably pip could not have an alias on the system depending on how it was installed, just a wild guess.

**Comment by gary-jackson** [comment]
This is probably the best way to call pip as a subprocess:

`subprocess.check_call([sys.executable, "-m", "pip", "install", "moduleA", "moduleB"])`

**Comment by jayvdb** [comment]
Created https://github.com/wolever/pip2pi/issues/100 for a longer-term solution.
