### ISSUE TITLE
cgi.escape was removed

### ISSUE THREAD

**Issue by wtnb75** [wolever/pip2pi#96]
`cgi.escape` is deprecated since python 3.2, and removed since python 3.8
https://docs.python.org/3.7/library/cgi.html#cgi.escape

```
# python --version
Python 3.8.0
# pip show pip2pi
Name: pip2pi
Version: 0.8.1
Summary: pip2pi builds a PyPI-compatible package repository from pip requirements
Home-page: https://github.com/wolever/pip2pi
Author: David Wolever
Author-email: david@wolever.net
License: BSD
Location: /usr/local/lib/python3.8/site-packages
Requires: pip
Required-by:
# dir2pi /some/dir/
Traceback (most recent call last):
  File "/usr/local/bin/dir2pi", line 8, in <module>
    sys.exit(dir2pi())
  File "/usr/local/lib/python3.8/site-packages/libpip2pi/commands.py", line 308, in dir2pi
    return _dir2pi(option, argv)
  File "/usr/local/lib/python3.8/site-packages/libpip2pi/commands.py", line 377, in _dir2pi
    cgi.escape(pkg_dir_name),
AttributeError: module 'cgi' has no attribute 'escape'
```

**Comment by jiujing** [comment]
in python3.8, you could change cgi.escape to cgi.html.escape in 3 lines——377,378 and 385 in the file “python3 path/site-packages/libpip2pi/commands.py”

**Comment by toabctl** [comment]
Same here. `pip2pi` is basically incompatible with newer python versions. So using a current Ubuntu and trying to execute `pip2pi` from an venv there fails:
```
+ dir2pi --normalize-package-names packages
Traceback (most recent call last):
  File "/root/parts/in-target-tgzs/build/.venv/bin/dir2pi", line 8, in <module>
    sys.exit(dir2pi())
  File "/root/parts/in-target-tgzs/build/.venv/lib/python3.8/site-packages/libpip2pi/commands.py", line 308, in dir2pi
    return _dir2pi(option, argv)
  File "/root/parts/in-target-tgzs/build/.venv/lib/python3.8/site-packages/libpip2pi/commands.py", line 377, in _dir2pi
    cgi.escape(pkg_dir_name),
AttributeError: module 'cgi' has no attribute 'escape'

```
